config/routes.rb
Rails.application.routes.draw do
  
  # devise_scope :user do
  #   get "register" => "devise/registrations#new", as: "new_user_registration"
  # end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  },
  path: ''

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
    get ':user/edit-profile' => 'devise/registrations#edit', :as => :edit_user_profile
    get 'sign_out', to: 'users/sessions#destroy'
  end

  root 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities
  resources :users
  


  # get 'signed-out', to: 'signouts#index'
  

  get 'user-profile', to: 'users#profile'
  
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  enum name: [:Running, :Yoga, :HIIT, :Cycling, :Weight_Training, :Swimming, :Hiking, :Jogging, :Pilates, :Dancing, :other]
  validates :name, presence: true
  validates :duration_minutes, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1440 }
  validates :date_field, presence: true


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user
  before_action :own_activity, only: [:edit, :update, :show, :destroy]
  # before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = @user.activities.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = @user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity has been successfully added.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, alert: 'Activity was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def get_user
      @user = current_user
    end

    def own_activity
      @activity = Activity.find(params[:id])
      unless current_user == @activity.user
        redirect_to(activities_path, alert: "You are not authorized to edit this activity.")
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    # def set_activity
    #     @activity = Activity.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :date_field, :duration_minutes )
    end

  end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<div class="container d-flex justify-content-center pb-5">
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <div class="form-group">
    
    <%= form.select :name, Activity.names.keys.map, prompt: "Please select an activity", class: "form-field" %>
  </div>

  <div class="form-group">
    <%= form.label "Date" %>
    <%= form.date_select :date_field %>
  </div>

  <div class="form-group">
    <%= form.label "Duration" %>
    <%= form.number_field :duration_minutes, min: 1, max: 1440 %> minutes
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/activities/edit.html.erb
<div class="jumbotron jumbotron-fluid display-2" id="act-edit-jumbo">Editing Activity</div>
<div class="container my-5" id="container">
<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path, class: "btn btn-outline-info" %>
</div>

app/views/activities/index.html.erb
<div class="jumbotron jumbotron-fluid display-2">
      Activities
    </div>
<div class=" container" id="container">
    <table class="container" id="activity-table">
      <thead class="jumbotron">
        <tr>
          <th>Activity</th>
          <th>Date</th>
          <th>Duration</th>
          <th></th>
        </tr>
      </thead>

      <tbody>

        <% @activities.each do |activity| %>

        <tr id="overlay">
          <td><%=  activity.name %></td>
          <td><%=  activity.date_field.to_formatted_s(:rfc822) %></td>
          <td>
            <%=  activity.duration_minutes %> minutes
          </td>
          <td id="activity-change">
            <%= link_to 'Edit', edit_activity_path(activity), id: 'lnk-yellow' %>
            <%= link_to 'x', activity, method: :delete, data: { confirm: 'Are you sure?' }, id:'del' %>
          </td>

        </tr>

        <% end %>

      </tbody>
    </table>

    <br>

    <span><%= link_to 'New Activity', new_activity_path, class: "btn btn-outline-success", id: 'lnk-green' %></span>
  </div>

app/views/activities/new.html.erb
<div class="jumbotron jumbotron-fluid display-2" id="act-new-jumbo">Add Activity</div>
<div class="container my-auto" id="container">
<div class="container py-5">
    <%= render 'form', activity: @activity %>

    <%= link_to 'Activity Diary', activities_path, class: "btn btn-outline-info", id: "lnk-theme" %>
</div>

app/views/activities/show.html.erb
<div class="jumbotron jumbotron-fluid display-2" id="act-show-jumbo">
  <%= @activity.date_field.to_formatted_s(:long) %>
</div>
<div class="container my-auto" id="container">

<div class="jumbotron d-flex flex-wrap justify-content-around display-4 p-5">

 <span> <%= @activity.name %></span><span> for </span><span><%= @activity.duration_minutes %> minutes</span>

</div>

<%= link_to 'Edit', edit_activity_path(@activity), class: "btn btn-outline-warning", id: "btn-yel" %>
<%= link_to 'Back', activities_path, class: "btn btn-outline-info", id: "lnk-theme" %>
</div>
</div>