config/routes.rb
Rails.application.routes.draw do
  
  # devise_scope :user do
  #   get "register" => "devise/registrations#new", as: "new_user_registration"
  # end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  },
  path: ''

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
    get ':user/edit-profile' => 'devise/registrations#edit', :as => :edit_user_profile
    get 'sign_out', to: 'users/sessions#destroy'
  end

  root 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities
  resources :users
  


  # get 'signed-out', to: 'signouts#index'
  

  get 'user-profile', to: 'users#profile'
  
end

app/views/layouts/_devise_notices.html.erb
<% if notice %>
    <div class="alert alert-success mb-0" role="alert">
        <%= notice %>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-danger mb-0" role="alert">
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
    <ul class="nav w-100 flex-fluid justify-content-between align-items-end">
    <div class="row">
        <li class="nav-item ml-3"><%= link_to show_img('fitness.svg'), root_path, class: "navbar-brand" %></li>
        </div>
            <div class="row justify-content-around mr-3">
        <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Your activity log", activities_path, class: "nav-link nav-lnk" %></li>
            <li class="nav-item"><%= link_to "View your profile", users_path, class: "nav-link nav-lnk" %></li>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, class: "nav-link nav-lnk" %></li>
        <% else %>
            <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "nav-link nav-lnk" %></li>
            <li class="nav-item"><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "nav-link nav-lnk" %></li>
            <li></li>
        <% end %>
        </div>
    </ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary nav-fill nav-justified mb-0">

    <%= link_to show_img('fitness.svg'), root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navcontrol"
        aria-controls="navcontrol" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navcontrol">
        <span class="navbar-nav mr-auto mt-2 mt-md-0">
        </span>

        <%= link_to "Home", root_path, class: "nav-link nav-lnk col-lg-2" %>

        <% if user_signed_in? %>
            <%= link_to "Activities", activities_path, class: "nav-link nav-lnk col-lg-2" %>


            <div class="nav-item dropdown col-lg-2">
                <% if has_avatar? %>
                    <%= link_to root_path, id: "navbar-dropdown", class: "nav-link nav-lnk dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
                        <%= image_tag current_user.avatar, id: "avatar" %><%= current_user.first_name %>
                    <% end %>
                <% else %>
                    <%= link_to current_user.first_name, root_path, id: "navbar-dropdown", class: "nav-link nav-lnk dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } %>
                <% end %>
                <div class="dropdown-menu w-100 bg-primary" aria-labelledby="navbar-dropdown">
                    <%= link_to "Profile", users_path, class: "dropdown-item text-align-center nav-lnk" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Sign Out",  destroy_user_session_path, class: "dropdown-item text-align-center nav-lnk" %>
                </div>


            <% else %>
                <%= link_to "Sign In", new_user_session_path, class: "nav-link nav-lnk col-md-2" %>
                <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "nav-link nav-lnk col-2" %>
            <% end %>


        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Move and Groove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'custom'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/devise_notices' %>
    </header>
    <main>
    <div class="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
    </main>
    <footer class="p-1">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>